import { and, eq, lt } from "drizzle-orm";
import { getDb, hasDatabaseUrl } from "../db";
import { appointments, availability, providerCalendarConnections, providerProfiles } from "../db/schema";
import { canManageProviderRecord } from "../lib/workspace";
import type { AuthenticatedActor } from "./auth";
import { CalendarConnectionError, CalendarProviderError, decryptRefreshToken, deterministicGoogleEventId, getGoogleAccessToken, googleCalendarRequest, isGoogleCalendarConfigured } from "./google-calendar";

const MAX_AVAILABILITY_RANGE_MS = 31 * 24 * 60 * 60 * 1000;
const CALENDAR_CONFIRMATION_LEASE_MS = 5 * 60 * 1000;
export class CalendarAuthorizationError extends Error {}
export class CalendarAvailabilityError extends Error {}
export function assertProviderOwnership(actor: AuthenticatedActor, ownerId: string) { if (!canManageProviderRecord(actor.role, actor.id, ownerId)) throw new CalendarAuthorizationError("You cannot manage this provider calendar."); }
export function assertAppointmentCanBeginCalendarConfirmation(status: string) { if (status !== "requested" && status !== "calendar_confirming") throw new CalendarAvailabilityError("Only requested appointments can be confirmed with Google Calendar."); }
export function shouldReuseCalendarEvent(externalCalendarEventId: string | null) { return Boolean(externalCalendarEventId); }
export function isCalendarConfirmationLeaseExpired(updatedAt: Date, now = new Date()) { return updatedAt.valueOf() <= now.valueOf() - CALENDAR_CONFIRMATION_LEASE_MS; }
export function validateAvailabilityRange(timeMin: Date, timeMax: Date, now = new Date()) { if (Number.isNaN(timeMin.valueOf()) || Number.isNaN(timeMax.valueOf()) || timeMin < now || timeMin >= timeMax || timeMax.valueOf() - timeMin.valueOf() > MAX_AVAILABILITY_RANGE_MS) throw new CalendarAvailabilityError("Availability must be a future range of 31 days or less."); }
async function connectionForProvider(providerId: string) { const [connection] = await getDb().select().from(providerCalendarConnections).where(eq(providerCalendarConnections.providerId, providerId)).limit(1); if (!connection) throw new CalendarConnectionError("This provider has not connected Google Calendar."); return connection; }
async function accessForProvider(providerId: string) { if (!isGoogleCalendarConfigured()) throw new CalendarAvailabilityError("Google Calendar is not configured."); const connection = await connectionForProvider(providerId); return { connection, accessToken: await getGoogleAccessToken(decryptRefreshToken(connection.encryptedRefreshToken)) }; }
async function providerOwner(providerId: string) { const [provider] = await getDb().select({ ownerId: providerProfiles.ownerId }).from(providerProfiles).where(eq(providerProfiles.id, providerId)).limit(1); if (!provider) throw new CalendarAvailabilityError("Provider not found."); return provider.ownerId; }
export async function assertCanViewProviderAvailability(actor: AuthenticatedActor, providerId: string) { const ownerId = await providerOwner(providerId); if (actor.role === "client") return; assertProviderOwnership(actor, ownerId); }
export async function getCalendarStatus(actor: AuthenticatedActor, providerId: string) { const ownerId = await providerOwner(providerId); assertProviderOwnership(actor, ownerId); const [connection] = await getDb().select({ calendarId: providerCalendarConnections.calendarId, updatedAt: providerCalendarConnections.updatedAt }).from(providerCalendarConnections).where(eq(providerCalendarConnections.providerId, providerId)).limit(1); return { configured: isGoogleCalendarConfigured(), connected: Boolean(connection), calendarId: connection?.calendarId, updatedAt: connection?.updatedAt }; }
export async function getProviderAvailability(actor: AuthenticatedActor, providerId: string, timeMin: Date, timeMax: Date) { if (!hasDatabaseUrl()) throw new CalendarAvailabilityError("Persistence is not configured."); validateAvailabilityRange(timeMin, timeMax); await assertCanViewProviderAvailability(actor, providerId); const { connection, accessToken } = await accessForProvider(providerId); const response = await googleCalendarRequest(accessToken, "/freeBusy", { method: "POST", body: JSON.stringify({ timeMin: timeMin.toISOString(), timeMax: timeMax.toISOString(), items: [{ id: connection.calendarId }] }) }); const payload = await response.json() as { calendars?: Record<string, { busy?: Array<{ start: string; end: string }> }> }; return { providerId, calendarId: connection.calendarId, busy: payload.calendars?.[connection.calendarId]?.busy ?? [] }; }
export async function confirmAppointmentWithCalendar(actor: AuthenticatedActor, appointmentId: string, createMeet = false) {
  const db = getDb(); let [appointment] = await db.select().from(appointments).where(eq(appointments.id, appointmentId)).limit(1); if (!appointment) throw new CalendarAvailabilityError("Appointment not found."); const ownerId = await providerOwner(appointment.providerId); assertProviderOwnership(actor, ownerId);
  if (shouldReuseCalendarEvent(appointment.externalCalendarEventId)) return { eventId: appointment.externalCalendarEventId!, reused: true };
  assertAppointmentCanBeginCalendarConfirmation(appointment.status);
  if (appointment.status === "calendar_confirming" && isCalendarConfirmationLeaseExpired(appointment.updatedAt)) { await db.update(appointments).set({ status: "requested", updatedAt: new Date() }).where(and(eq(appointments.id, appointment.id), eq(appointments.status, "calendar_confirming"), lt(appointments.updatedAt, new Date(Date.now() - CALENDAR_CONFIRMATION_LEASE_MS)))); [appointment] = await db.select().from(appointments).where(eq(appointments.id, appointmentId)).limit(1); if (!appointment) throw new CalendarAvailabilityError("Appointment not found."); }
  if (appointment.status === "requested") { const claimed = await db.update(appointments).set({ status: "calendar_confirming", updatedAt: new Date() }).where(and(eq(appointments.id, appointment.id), eq(appointments.status, "requested"))).returning({ id: appointments.id }); if (!claimed.length) { [appointment] = await db.select().from(appointments).where(eq(appointments.id, appointmentId)).limit(1); if (!appointment || appointment.status !== "calendar_confirming") throw new CalendarAvailabilityError("Only requested appointments can be confirmed with Google Calendar."); } }
  if (!appointment.availabilityId) throw new CalendarAvailabilityError("An availability slot is required before calendar confirmation."); const [slot] = await db.select().from(availability).where(and(eq(availability.id, appointment.availabilityId), eq(availability.providerId, appointment.providerId))).limit(1); if (!slot) throw new CalendarAvailabilityError("Availability does not belong to this provider.");
  const { connection, accessToken } = await accessForProvider(appointment.providerId); const params = createMeet ? "?conferenceDataVersion=1" : ""; const eventId = deterministicGoogleEventId(appointment.id); const event = { id: eventId, summary: "CraftDirectory consultation", start: { dateTime: slot.startsAt.toISOString() }, end: { dateTime: slot.endsAt.toISOString() }, extendedProperties: { private: { craftDirectoryAppointmentId: appointment.id } }, ...(createMeet ? { conferenceData: { createRequest: { requestId: appointment.id } } } : {}) };
  let result: { id?: string; htmlLink?: string }; try { const response = await googleCalendarRequest(accessToken, `/calendars/${encodeURIComponent(connection.calendarId)}/events${params}`, { method: "POST", body: JSON.stringify(event) }); result = await response.json() as { id?: string; htmlLink?: string }; } catch (error) { if (!(error instanceof CalendarProviderError) || error.status !== 409) throw error; const response = await googleCalendarRequest(accessToken, `/calendars/${encodeURIComponent(connection.calendarId)}/events/${eventId}`); result = await response.json() as { id?: string; htmlLink?: string }; }
  if (!result.id) throw new CalendarProviderError("Google Calendar did not return an event identifier."); const persisted = await db.update(appointments).set({ status: "confirmed", externalCalendarEventId: result.id, externalCalendarEventUrl: result.htmlLink ?? null, updatedAt: new Date() }).where(and(eq(appointments.id, appointment.id), eq(appointments.status, "calendar_confirming"))).returning({ externalCalendarEventId: appointments.externalCalendarEventId, externalCalendarEventUrl: appointments.externalCalendarEventUrl });
  if (!persisted.length) { const [current] = await db.select().from(appointments).where(eq(appointments.id, appointment.id)).limit(1); if (current?.externalCalendarEventId) return { eventId: current.externalCalendarEventId, eventUrl: current.externalCalendarEventUrl ?? undefined, reused: true }; throw new CalendarAvailabilityError("Calendar confirmation changed concurrently; retry safely."); }
  return { eventId: result.id, eventUrl: result.htmlLink, reused: result.id === eventId };
}
