import { afterEach, describe, expect, it } from "vitest";
import { createGoogleAuthorizationUrl, decryptRefreshToken, encryptRefreshToken, signOAuthState, verifyOAuthState } from "../src/server/google-calendar";
import { CalendarAuthorizationError, assertAppointmentCanBeginCalendarConfirmation, assertProviderOwnership, isCalendarConfirmationLeaseExpired, shouldReuseCalendarEvent } from "../src/server/calendar-service";
import { deterministicGoogleEventId } from "../src/server/google-calendar";
import { CalendarAvailabilityError, validateAvailabilityRange } from "../src/server/calendar-service";
import { isActiveCalendarChannel } from "../app/api/calendar/google/webhook/route";
import { availabilityErrorStatus } from "../app/api/providers/[providerId]/availability/route";
import { CalendarConfigurationError, CalendarConnectionError, exchangeAuthorizationCode } from "../src/server/google-calendar";
import { classifyCalendarCallbackFailure, logCalendarCallbackFailure } from "../src/server/calendar-callback-logging";

const original = { ...process.env };
afterEach(() => { process.env = { ...original }; });
function configure() { process.env.GOOGLE_CALENDAR_CLIENT_ID = "client"; process.env.GOOGLE_CALENDAR_CLIENT_SECRET = "secret"; process.env.GOOGLE_CALENDAR_TOKEN_ENCRYPTION_KEY = Buffer.alloc(32, 7).toString("base64"); process.env.GOOGLE_CALENDAR_STATE_SECRET = "state-secret"; }
describe("Google Calendar OAuth safety", () => {
  it("builds an authorization URL with signed state and least-privilege calendar scopes", () => { configure(); const state = signOAuthState({ providerId: "provider-1", userId: "user-1", nonce: "nonce-1234567890", exp: Date.now() + 60_000 }); const url = new URL(createGoogleAuthorizationUrl(state, "https://app.test/api/calendar/google/callback")); expect(url.origin).toBe("https://accounts.google.com"); expect(url.searchParams.get("state")).toBe(state); expect(url.searchParams.get("scope")).toContain("calendar.freebusy"); expect(url.searchParams.get("scope")).toContain("/auth/calendar"); expect(verifyOAuthState(state)?.providerId).toBe("provider-1"); });
  it("rejects tampered and expired state", () => { configure(); const valid = signOAuthState({ providerId: "p", userId: "u", nonce: "n", exp: Date.now() + 60_000 }); expect(verifyOAuthState(`${valid}x`)).toBeNull(); expect(verifyOAuthState(signOAuthState({ providerId: "p", userId: "u", nonce: "nonce-1234567890", exp: Date.now() - 1 }))).toBeNull(); });
  it("requires a structurally valid, high-entropy OAuth nonce", () => { configure(); expect(verifyOAuthState(signOAuthState({ providerId: "p", userId: "u", nonce: "short", exp: Date.now() + 60_000 }))).toBeNull(); });
  it("encrypts refresh tokens with authenticated encryption", () => { configure(); const encrypted = encryptRefreshToken("refresh-token"); expect(encrypted).not.toContain("refresh-token"); expect(decryptRefreshToken(encrypted)).toBe("refresh-token"); expect(() => decryptRefreshToken(`${encrypted}x`)).toThrow(); });
  it("authorizes calendar management only for the provider owner or an admin", () => { expect(() => assertProviderOwnership({ id: "owner", role: "provider" }, "owner")).not.toThrow(); expect(() => assertProviderOwnership({ id: "other", role: "provider" }, "owner")).toThrow(CalendarAuthorizationError); expect(() => assertProviderOwnership({ id: "admin", role: "admin" }, "owner")).not.toThrow(); });
  it("bounds availability to a future 31-day window", () => { const now = new Date("2026-01-01T00:00:00Z"); expect(() => validateAvailabilityRange(new Date("2026-01-02T00:00:00Z"), new Date("2026-01-10T00:00:00Z"), now)).not.toThrow(); expect(() => validateAvailabilityRange(new Date("2025-12-31T00:00:00Z"), new Date("2026-01-02T00:00:00Z"), now)).toThrow(CalendarAvailabilityError); expect(() => validateAvailabilityRange(new Date("2026-01-02T00:00:00Z"), new Date("2026-02-03T00:00:00Z"), now)).toThrow(CalendarAvailabilityError); });
  it("derives a stable valid event ID for retry reconciliation", () => { expect(deterministicGoogleEventId("appointment-1")).toMatch(/^[a-v0-9]{32,102}$/); expect(deterministicGoogleEventId("appointment-1")).toBe(deterministicGoogleEventId("appointment-1")); });
  it("allows only requested confirmation state and rejects terminal states", () => { expect(() => assertAppointmentCanBeginCalendarConfirmation("requested")).not.toThrow(); for (const status of ["confirmed", "cancelled", "declined"]) expect(() => assertAppointmentCanBeginCalendarConfirmation(status)).toThrow(CalendarAvailabilityError); });
  it("rejects expired webhook channels", () => { const now = new Date("2026-01-01T00:00:00Z"); expect(isActiveCalendarChannel(new Date("2026-01-01T00:00:01Z"), now)).toBe(true); expect(isActiveCalendarChannel(new Date("2025-12-31T23:59:59Z"), now)).toBe(false); expect(isActiveCalendarChannel(null, now)).toBe(false); });
  it("reuses a persisted event on confirmed retry and detects stale confirmation leases", () => { expect(shouldReuseCalendarEvent("event-1")).toBe(true); expect(shouldReuseCalendarEvent(null)).toBe(false); const now = new Date("2026-01-01T00:10:00Z"); expect(isCalendarConfirmationLeaseExpired(new Date("2026-01-01T00:04:59Z"), now)).toBe(true); expect(isCalendarConfirmationLeaseExpired(new Date("2026-01-01T00:05:01Z"), now)).toBe(false); });
  it("maps availability failures to non-leaky HTTP statuses", () => { expect(availabilityErrorStatus(new CalendarAvailabilityError("Availability must be a future range of 31 days or less."))).toBe(400); expect(availabilityErrorStatus(new CalendarAvailabilityError("Persistence is not configured."))).toBe(503); expect(availabilityErrorStatus(new CalendarAvailabilityError("Provider not found."))).toBe(404); expect(availabilityErrorStatus(new CalendarConnectionError("missing"))).toBe(409); expect(availabilityErrorStatus(new CalendarConfigurationError("client_id_missing"))).toBe(503); expect(availabilityErrorStatus(new CalendarAuthorizationError())).toBe(403); });
  it("uses fixed configuration codes for missing or invalid OAuth settings", async () => {
    delete process.env.GOOGLE_CALENDAR_CLIENT_ID;
    expect(() => createGoogleAuthorizationUrl("state", "https://app.test/callback")).toThrowError(expect.objectContaining({ code: "client_id_missing" }));
    configure(); delete process.env.GOOGLE_CALENDAR_CLIENT_SECRET;
    await expect(exchangeAuthorizationCode("authorization-code", "https://app.test/callback")).rejects.toMatchObject({ code: "client_secret_missing" });
    configure(); delete process.env.GOOGLE_CALENDAR_STATE_SECRET;
    expect(() => signOAuthState({ providerId: "p", userId: "u", nonce: "nonce-1234567890", exp: Date.now() + 60_000 })).toThrowError(expect.objectContaining({ code: "state_secret_missing" }));
    configure(); delete process.env.GOOGLE_CALENDAR_TOKEN_ENCRYPTION_KEY;
    expect(() => encryptRefreshToken("refresh-token")).toThrowError(expect.objectContaining({ code: "encryption_key_missing" }));
    configure(); process.env.GOOGLE_CALENDAR_TOKEN_ENCRYPTION_KEY = "not-base64!";
    expect(() => encryptRefreshToken("refresh-token")).toThrowError(expect.objectContaining({ code: "encryption_key_invalid" }));
    process.env.GOOGLE_CALENDAR_TOKEN_ENCRYPTION_KEY = Buffer.alloc(31, 7).toString("base64");
    expect(() => encryptRefreshToken("refresh-token")).toThrowError(expect.objectContaining({ code: "encryption_key_invalid" }));
  });
  it("logs only fixed callback codes and never raw error details", () => { const secret = "code=secret-code refresh_token=secret-token provider=user-1"; expect(classifyCalendarCallbackFailure(new CalendarConfigurationError("client_id_missing"), "token_exchange")).toBe("client_id_missing"); expect(classifyCalendarCallbackFailure(new Error(secret), "token_exchange")).toBe("token_exchange_rejected"); expect(classifyCalendarCallbackFailure(new Error(secret), "encryption")).toBe("encryption_failed"); expect(classifyCalendarCallbackFailure(new Error(secret), "database")).toBe("database_persist_failed"); const logs: string[] = []; logCalendarCallbackFailure(new Error(secret), "token_exchange", (entry) => logs.push(entry)); expect(logs).toEqual([JSON.stringify({ level: "error", event: "google_calendar_oauth_callback_failed", code: "token_exchange_rejected" })]); expect(logs[0]).not.toContain("secret"); expect(logs[0]).not.toContain("user-1"); expect(logs[0]).not.toContain("refresh_token"); });
});
