"use client";

import Image from "next/image";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { handleDirectoryCommand } from "../src/lib/assistant";
import { createProvider, deleteProvider, filterProviders, providers as seedProviders, updateProvider, type Provider, type Role } from "../src/lib/directory";
import { canBookAppointment, canManageProvider, canViewAppointments, canViewRequirements } from "../src/lib/permissions";
import { confirmCalendarAppointment, createPersistedProvider, createWorkspaceRecord, fetchProviderAvailability, fetchProviders, fetchSession, fetchWorkspace, getMutationNotice, linkGoogleAccount, managementIdentity, mutateProvider, patchWorkspaceRecord, type SessionPayload, type WorkspaceAppointment, type WorkspaceRequirement } from "../src/lib/client-session";
import { catalog, localizedPath, type Locale } from "../src/lib/i18n";

const roles: Role[] = ["visitor", "client", "provider", "admin"];
const categories = ["All categories", "Landscape", "Interior Design", "General Contractor"];
const locations = ["All locations", "Austin", "Chicago", "Denver"];

type View = "directory" | "requirements" | "appointments" | "manage";
export default function DirectoryApp({ locale = "en" }: { locale?: Locale }) {
  const copy = catalog(locale);
  const [role, setRole] = useState<Role>("visitor"); const [view, setView] = useState<View>("directory");
  const [items, setItems] = useState<Provider[]>(seedProviders); const [query, setQuery] = useState(""); const [category, setCategory] = useState("All categories"); const [location, setLocation] = useState("All locations");
  const [selected, setSelected] = useState<Provider | null>(null); const [notice, setNotice] = useState(""); const [message, setMessage] = useState(""); const [assistantReply, setAssistantReply] = useState<string>(copy.assistant.initial); const [isAssistantMinimized, setIsAssistantMinimized] = useState(false);
  const [editing, setEditing] = useState<Provider | null>(null);
  const [session, setSession] = useState<SessionPayload | null>(null);
  const [requirements, setRequirements] = useState<WorkspaceRequirement[]>([]);
  const [appointments, setAppointments] = useState<WorkspaceAppointment[]>([]);
  useEffect(() => { let mounted = true; const accountResult = new URLSearchParams(window.location.search).get("account"); if (accountResult === "linked") setNotice("Google account linked successfully."); if (accountResult === "link-failed") setNotice("Google account linking failed. Try again."); fetchSession().then(async (nextSession) => { if (!mounted) return; setSession(nextSession); const [persisted, nextRequirements, nextAppointments] = await Promise.all([fetchProviders(), nextSession?.user ? fetchWorkspace<WorkspaceRequirement>(fetch, "requirements") : Promise.resolve(null), nextSession?.user ? fetchWorkspace<WorkspaceAppointment>(fetch, "appointments") : Promise.resolve(null)]); if (!mounted) return; if (persisted) setItems(persisted); if (nextRequirements) setRequirements(nextRequirements); if (nextAppointments) setAppointments(nextAppointments); }).catch(() => mounted && setSession(null)); return () => { mounted = false; }; }, []);
  const results = useMemo(() => filterProviders(items, { query, category: category === "All categories" ? undefined : category, location: location === "All locations" ? undefined : location }), [items, query, category, location]);
  const identity = managementIdentity(session, { id: role === "provider" ? "green-horizon" : "", role });
  const isSessionMode = identity.source === "session";
  const navigate = (next: View) => { if (next === "requirements" && !canViewRequirements(identity.role)) return setNotice("Requirements are available in Client, Provider, or Admin mode."); if (next === "appointments" && !canViewAppointments(identity.role)) return setNotice("Appointments are available in Client, Provider, or Admin mode."); if (next === "manage" && identity.role !== "provider" && identity.role !== "admin") return setNotice(isSessionMode ? "Your account cannot manage provider listings." : "Manage listings is available in Provider or Admin demo mode."); setNotice(""); setView(next); };
  const askAssistant = (event: FormEvent) => { event.preventDefault(); if (!message.trim()) return; const response = handleDirectoryCommand(message, identity.role, locale); setAssistantReply(response.reply); setMessage(""); if (response.filters) { setQuery(response.filters.query ?? ""); setCategory(response.filters.category ?? "All categories"); setLocation(response.filters.location ?? "All locations"); } if (response.open) navigate(response.open); };
  const addProvider = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const input = { name: String(data.get("name")), category: String(data.get("category")), location: String(data.get("location")), description: String(data.get("description")) }; if (isSessionMode) { const response = await createPersistedProvider(fetch, input); if (!response.ok) return setNotice(getMutationNotice(response.status)); const next = await response.json() as Provider; setItems((current) => [next, ...current]); event.currentTarget.reset(); return setNotice("Listing created in your authenticated session."); } const next = createProvider({ ...input, image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=80", services: ["Consultation", "Project planning"], ownerId: identity.role === "provider" ? identity.id : "admin" }); setItems((current) => [next, ...current]); event.currentTarget.reset(); setNotice("Listing created in this local demo session."); };
  const saveProvider = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!editing) return; const data = new FormData(event.currentTarget); const patch = { name: String(data.get("name")), category: String(data.get("category")), location: String(data.get("location")), description: String(data.get("description")) }; if (isSessionMode) { const response = await mutateProvider(fetch, editing.id, "PATCH", patch); if (!response.ok) return setNotice(getMutationNotice(response.status)); const updated = { ...editing, ...patch }; setItems((current) => current.map((item) => item.id === updated.id ? updated : item)); setEditing(null); return setNotice("Listing updated in your authenticated session."); } const updated = updateProvider(items, editing.id, patch, identity.role, identity.id); if (!updated) return setNotice("You do not have permission to edit this listing."); setItems((current) => current.map((item) => item.id === updated.id ? updated : item)); setEditing(null); setNotice("Listing updated in this local demo session."); };
  const removeProvider = async (provider: Provider) => { if (isSessionMode) { const response = await mutateProvider(fetch, provider.id, "DELETE"); if (!response.ok) return setNotice(getMutationNotice(response.status)); setItems((current) => current.filter((item) => item.id !== provider.id)); if (editing?.id === provider.id) setEditing(null); return setNotice("Listing deleted in your authenticated session."); } const next = deleteProvider(items, provider.id, identity.role, identity.id); if (!next) return setNotice("You do not have permission to delete this listing."); setItems(next); if (editing?.id === provider.id) setEditing(null); setNotice("Listing deleted in this local demo session."); };
  const createRequirement = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const response = await createWorkspaceRecord(fetch, "requirements", { title: String(data.get("title")), details: String(data.get("details")), providerId: String(data.get("providerId") || "") }); if (!response.ok) return setNotice(getMutationNotice(response.status)); const record = await response.json() as WorkspaceRequirement; setRequirements((current) => [record, ...current]); event.currentTarget.reset(); setNotice("Requirement saved and shared with its selected provider."); };
  const updateRequirementStatus = async (id: string, status: string) => { const response = await patchWorkspaceRecord(fetch, "requirements", id, { status }); if (!response.ok) return setNotice(getMutationNotice(response.status)); setRequirements((current) => current.map((item) => item.id === id ? { ...item, status } : item)); };
  const requestAppointment = async (providerId: string) => { const response = await createWorkspaceRecord(fetch, "appointments", { providerId }); if (!response.ok) return setNotice(getMutationNotice(response.status)); const record = await response.json() as WorkspaceAppointment; setAppointments((current) => [record, ...current]); setSelected(null); setView("appointments"); setNotice("Consultation request saved. Calendar and email delivery are not connected."); };
  const checkAvailability = async (providerId: string) => { const now = new Date(); const result = await fetchProviderAvailability(fetch, providerId, now.toISOString(), new Date(now.valueOf() + 7 * 86400000).toISOString()); setNotice(result ? `Google Calendar is connected. ${result.busy.length} busy period(s) found in the next 7 days.` : "Calendar availability is not connected for this provider."); };
  const linkProviderGoogleAccount = async () => { const result = await linkGoogleAccount(fetch); if (!result.ok || !result.url) return setNotice(result.message ?? "Google account linking is unavailable. Configure Google sign-in first."); window.location.assign(result.url); };
  const updateAppointmentStatus = async (id: string, status: string) => { const response = await patchWorkspaceRecord(fetch, "appointments", id, { status }); if (!response.ok) return setNotice(getMutationNotice(response.status)); setAppointments((current) => current.map((item) => item.id === id ? { ...item, status } : item)); };
  const confirmAppointmentOnCalendar = async (id: string) => { const response = await confirmCalendarAppointment(fetch, id); if (!response.ok) return setNotice(response.status === 409 ? "A connected calendar and selected availability slot are required to create an event." : getMutationNotice(response.status)); setAppointments((current) => current.map((item) => item.id === id ? { ...item, status: "confirmed" } : item)); setNotice("Google Calendar event confirmed. Email delivery is not configured."); };
  const signOut = async () => { await fetch("/api/auth/sign-out", { method: "POST", credentials: "include" }); setSession(null); setRequirements([]); setAppointments([]); setNotice("Signed out. Demo mode is available for preview only."); };
  return <main>
    <header className="topbar"><a className="brand" onClick={() => navigate("directory")}>craft<span>directory</span></a><nav>{(["directory", "requirements", "appointments", "manage"] as View[]).map((item) => <button key={item} className={view === item ? "nav active" : "nav"} onClick={() => navigate(item)}>{item === "directory" ? copy.navigation.directory : item === "requirements" ? copy.navigation.requirements : item === "appointments" ? copy.navigation.appointments : copy.navigation.manage}</button>)}</nav>{isSessionMode ? <button className="nav" onClick={signOut}>{copy.navigation.signOut}{identity.name ? ` (${identity.name})` : ""}</button> : <a className="nav" href={localizedPath("auth", locale)}>{copy.navigation.signIn}</a>}{!isSessionMode && <label className="role">Demo role (no session)<select value={role} onChange={(e) => { setRole(e.target.value as Role); setNotice(""); }} >{roles.map((item) => <option key={item}>{item}</option>)}</select></label>}</header>
    <section className="hero"><p className="eyebrow">{copy.hero.eyebrow}</p><h1>{copy.hero.title.split("\n").map((line) => <span key={line}>{line}<br/></span>)}</h1><p>{copy.hero.description}</p></section>
    {notice && <div className="notice">{notice}</div>}
    {view === "directory" && <><section className="search"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={copy.search.query}/><select value={category} onChange={(e) => setCategory(e.target.value)}>{categories.map((item) => <option value={item} key={item}>{locale === "es" && item === "All categories" ? copy.search.category : item}</option>)}</select><select value={location} onChange={(e) => setLocation(e.target.value)}>{locations.map((item) => <option value={item} key={item}>{locale === "es" && item === "All locations" ? copy.search.location : item}</option>)}</select><button className="primary">{copy.search.submit}</button></section><section className="result-head"><strong>{results.length} {copy.search.result}</strong><span>{copy.search.curated}</span></section><section className="grid">{results.map((provider) => <article className="card" key={provider.id}><div className="image-wrap"><Image src={provider.image} alt={provider.name} fill sizes="(max-width: 800px) 100vw, 33vw"/></div><div className="card-body"><p className="eyebrow">{provider.category} · {provider.location}</p><h2>{provider.name}</h2><p className="rating">★ {provider.rating} <span>({provider.reviews} reviews)</span></p><p>{provider.description}</p><button className="text-button" onClick={() => setSelected(provider)}>{locale === "es" ? "Ver perfil →" : "View profile →"}</button></div></article>)}</section></>}
    {view === "requirements" && <section className="workspace"><p className="eyebrow">PROJECT REQUIREMENTS</p><h2>{isSessionMode ? "Your persisted project briefs." : "Sign in to save and share project briefs."}</h2>{isSessionMode && identity.role === "client" && <form className="provider-form" onSubmit={createRequirement}><input required name="title" placeholder="Project title"/><textarea required name="details" placeholder="Goals, scope, budget, and timing"/><select name="providerId"><option value="">Keep private for now</option>{items.map((provider) => <option value={provider.id} key={provider.id}>{provider.name}</option>)}</select><button className="primary">Save requirement</button></form>}<div className="two-col">{requirements.map((item) => <article key={item.id}><b>{item.title}</b><p>{item.details}</p><p className="fine">Status: {item.status}</p>{(identity.role === "provider" || identity.role === "admin") && <select value={item.status} onChange={(event) => updateRequirementStatus(item.id, event.target.value)}>{["submitted", "reviewing", "accepted", "closed"].map((status) => <option key={status}>{status}</option>)}</select>}</article>)}{!requirements.length && <article><p>{isSessionMode ? "No requirements are available for this workspace." : "Requirements are demo-only until you sign in."}</p></article>}</div></section>}
    {view === "appointments" && <section className="workspace"><p className="eyebrow">APPOINTMENTS</p><h2>{isSessionMode ? "Consultation requests." : "Sign in to request a consultation."}</h2><div className="two-col">{appointments.map((item) => <article key={item.id}><b>Provider: {items.find((provider) => provider.id === item.providerId)?.name ?? item.providerId}</b><p>Status: {item.status}</p>{identity.role === "client" && item.status === "requested" && <button className="text-button" onClick={() => updateAppointmentStatus(item.id, "cancelled")}>Cancel request</button>}{(identity.role === "provider" || identity.role === "admin") && item.status === "requested" && <><button className="text-button" onClick={() => confirmAppointmentOnCalendar(item.id)}>Confirm with Google Calendar</button><button className="text-button" onClick={() => updateAppointmentStatus(item.id, "confirmed")}>Confirm locally</button><button className="text-button" onClick={() => updateAppointmentStatus(item.id, "declined")}>Decline</button></>}</article>)}{!appointments.length && <article><p>{isSessionMode ? "No consultation requests are available." : "Appointments are demo-only until you sign in."}</p></article>}<article><b>Calendar delivery</b><p>A request is local only. A connected provider calendar and a selected availability slot are required before confirmation creates an external event; email delivery is not configured.</p></article></div></section>}
    {view === "manage" && <section className="workspace"><p className="eyebrow">LISTING MANAGEMENT</p><h2>{editing ? `Edit ${editing.name}` : isSessionMode ? "Manage provider listings." : "Add a provider listing."}</h2>{isSessionMode && identity.role === "provider" && <button className="text-button" onClick={linkProviderGoogleAccount}>Link Google sign-in</button>}{editing ? <form className="provider-form" onSubmit={saveProvider}><input required name="name" defaultValue={editing.name}/><select name="category" defaultValue={editing.category}>{categories.slice(1).map((item) => <option key={item}>{item}</option>)}</select><select name="location" defaultValue={editing.location}>{locations.slice(1).map((item) => <option key={item}>{item}</option>)}</select><textarea required name="description" defaultValue={editing.description}/><button className="primary">{isSessionMode ? "Save changes" : "Save local changes"}</button><button type="button" className="text-button" onClick={() => setEditing(null)}>Cancel</button></form> : (!isSessionMode || identity.role === "provider" || identity.role === "admin") && <form className="provider-form" onSubmit={addProvider}><input required name="name" placeholder="Business name"/><select name="category">{categories.slice(1).map((item) => <option key={item}>{item}</option>)}</select><select name="location">{locations.slice(1).map((item) => <option key={item}>{item}</option>)}</select><textarea required name="description" placeholder="Short description"/><button className="primary">{isSessionMode ? "Create listing" : "Create local listing"}</button></form>}<div className="two-col">{items.filter((provider) => canManageProvider(identity.role, identity.id, provider.ownerId)).map((provider) => <article key={provider.id}><b>{provider.name}</b><p>{provider.category} · {provider.location}</p>{isSessionMode && <a className="text-button" href={`/api/calendar/google/connect?providerId=${encodeURIComponent(provider.id)}`}>Connect Google Calendar</a>}<button className="text-button" onClick={() => setEditing(provider)}>Edit</button><button className="text-button" onClick={() => removeProvider(provider)}>Delete</button></article>)}</div><p className="fine">{isSessionMode ? "Authenticated provider listings load from and mutate through the server API." : "Demo role controls are preview-only. Sign in to use persisted provider mutations."}</p></section>}
    {isAssistantMinimized ? <button className="assistant-restore" type="button" aria-label={copy.assistant.restore} aria-controls="project-concierge" aria-expanded="false" onClick={() => setIsAssistantMinimized(false)}>{copy.assistant.restore}</button> : <aside id="project-concierge" className="assistant"><div className="assistant-header"><div><p className="eyebrow">{copy.assistant.eyebrow}</p><strong>{copy.assistant.title}</strong></div><button className="assistant-minimize" type="button" aria-label={copy.assistant.minimize} aria-controls="project-concierge" aria-expanded="true" onClick={() => setIsAssistantMinimized(true)}>{copy.assistant.minimize}</button></div><p>{assistantReply}</p><form onSubmit={askAssistant}><input value={message} onChange={(e) => setMessage(e.target.value)} placeholder={copy.assistant.placeholder}/><button aria-label={copy.assistant.send}>→</button></form><small>Local typed command demo. Set <code>EVE_MODEL</code>, auth, and provider integrations for production.</small></aside>}
    {selected && <div className="overlay" onClick={() => setSelected(null)}><section className="profile" onClick={(e) => e.stopPropagation()}><button className="close" onClick={() => setSelected(null)}>×</button><div className="profile-image"><Image src={selected.image} alt={selected.name} fill sizes="600px"/></div><p className="eyebrow">{selected.category} · {selected.location}</p><h2>{selected.name}</h2><p className="rating">★ {selected.rating} ({selected.reviews} reviews)</p><p>{selected.description}</p><h3>Services</h3><p>{selected.services.join(" · ")}</p>{isSessionMode && identity.role === "client" && <button className="text-button" onClick={() => checkAvailability(selected.id)}>Check Google Calendar availability</button>}{isSessionMode && identity.role === "client" ? <button className="primary" onClick={() => requestAppointment(selected.id)}>Request consultation</button> : canBookAppointment(identity.role) ? <a className="primary" href="/auth">Sign in to request consultation</a> : <p className="fine">Sign in as a Client to request a consultation.</p>}{canManageProvider(identity.role, identity.id, selected.ownerId) && <button className="text-button" onClick={() => { setEditing(selected); setSelected(null); navigate("manage"); }}>Manage this listing →</button>}</section></div>}
  </main>;
}
